POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "lol",
    "important": true
}

###
GET http://localhost:3001/api/notes/

###
PUT http://localhost:3001/api/notes/65d9f767a2ca36009a5679d9
Content-Type: application/json

{
    "important": true,
    "content": "LOL"
}

###
DELETE https://express-phonebook-cool-dust-4054.fly.dev/api/persons/65da1a72b57ad45f75ebe5cd

### 
DELETE http://localhost:3001/api/notes/65d82d481e4d48fc3f2a722a

###
GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "test_user",
    "name": "John",
    "password": "test_user1"
}
###
POST http://localhost:3001/api/users/
Content-Type: application/json

{
    "username": "test_user2",
    "name": "James",
    "password": "test_user2"
}
###
POST http://localhost:3001/api/notes
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RfdXNlcjIiLCJpZCI6IjY2MDMzY2E5YTRlYWVkZDZkZjNjZTg3YSIsImlhdCI6MTcxMTQ4ODE4NX0.wLGGdWGRNFdjluCrvNQw1zwTEPwSwF2e2lzqQPFp-sg

{
    "content": "No Token POST",
    "important": true
}
### 
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "test_user2",
    "password": "test_user2"
}